### ISSUE TITLE
Remove redundant parens in class constraint removes only ending one

### ISSUE THREAD

**Issue by jneira** [mpickering/apply-refact#112]
* From https://github.com/haskell/haskell-language-server/issues/1844 by @augustss

### Steps to reproduce
Use this file:
```haskell
module M where
import GHC.Stack
foo :: (HasCallStack) => Int
foo = undefined
```
Apply the suggest refactoring to remove redundant parens.

### Expected behaviour
The result should be
```
foo :: HasCallStack => Int
```

### Actual behaviour
The result is
```
foo :: (HasCallStack => Int
```

**Comment by zliu41** [comment]
Thanks for the bug report. Looks like a corner case - this is the only case where brackets are removed from the entire context (`foo :: (Eq a) => ...` doesn't trigger HLint, for example). I'll take a closer look tomorrow.

**Comment by zliu41** [comment]
@jneira This is fixed in #113 and I just released 0.9.3.0.

**Comment by jneira** [comment]
Wow, that was really fast, as always, many thanks and congrats for your work

**Comment by augustss** [comment]
Thanks!
