### ISSUE TITLE
Build failure on GHC 9.2

### ISSUE THREAD

**Issue by ndmitchell** [mpickering/apply-refact#114]
HLint is seeing build failures with GHC 9.2 on Windows, Mac and Linux. CC @zliu41 @alanz 

https://github.com/ndmitchell/hlint/actions

**Comment by zliu41** [comment]
@alanz Could you help me understand how we should go about migrating to the latest version of ghc-exactprint? For example, the `Anns` type is gone, and it doesn't appear to be part of the GHC 9.2.1 API either, so what should be used instead?

**Comment by alanz** [comment]
I will take a look in the morning

**Comment by alanz** [comment]
My work in progress is in #116 .

**Comment by andreasabel** [comment]
Sample build failure reported in the OP: https://github.com/ndmitchell/hlint/runs/4691040973?check_suite_focus=true#step:8:286

**Comment by LeventErkok** [comment]
@alanz Any chance this'll get any updates soon? hlint has been stuck on pre-9.2.1 for quite some time now. Thanks!

**Comment by zliu41** [comment]
0.10.0.0 has been released.
