### ISSUE TITLE
Refactoring of monadic code results in code that is parenthesized erroneously

### ISSUE THREAD

**Issue by Aster89** [mpickering/apply-refact#124]
The code
```haskell
f = const [] . (>>= const Nothing) . const Nothing
```
is refactored to
```haskell
f = const [] . const Nothing <=< const Nothing
```
which is wrong, instead of
```haskell
f = const [] . (const Nothing <=< const Nothing)
```
which is correct.

Originally filed the report on [HLS](https://github.com/haskell/haskell-language-server/issues/2791).

**Comment by zliu41** [comment]
Thanks for reporting the bug, @Aster89. I believe this should be taken care of on the HLint side, so I opened https://github.com/ndmitchell/hlint/issues/1364.

**Comment by zliu41** [comment]
The fix has been merged into HLint master.
