### ISSUE TITLE
Refactoring may introduce not imported name

### ISSUE THREAD

**Issue by phadej** [mpickering/apply-refact#15]
``` hs
module Test (foo) where

foo :: (Int, a) -> (Int, b)
foo (x, y) = (\(x, y) -> (abs x, y)) (x + 1, y + 1)
```

is refactored into

``` hs
module Test (foo) where

foo :: (Int, a) -> (Int, b)
foo (x, y) = (Control.Arrow.first abs) (x + 1, y + 1)
```

**Comment by mpickering** [comment]
Yep, although this is what hlint suggests. It might be worth adding a flag to hlint which only suggests things which will certainly be in scope to avoid situations like this.

**Comment by zliu41** [comment]
Related: https://github.com/ndmitchell/hlint/issues/1001
Going to close this, since this is purely an HLint issue.
