### ISSUE TITLE
Refactor option --pos does not work with warning location

### ISSUE THREAD

**Issue by mrBliss** [mpickering/apply-refact#20]
When calling `hlint Bug.hs` with `Bug.hs` containing:
```haskell
module Bug where
bar n = 1 + (bar n)
```
I get:
```
Bug.hs:2:9: Warning: Redundant bracket
Found:
  1 + (bar n)
Why not:
  1 + bar n

1 suggestion
```

Fine, that's what I expected. Now lets apply the hint with `--refactor` but also with the `--pos` suggested by the warning.
```
$ hlint Bug.hs --refactor  --refactor-options="--pos 2,9" 

module Bug where
bar n = 1 + (bar n)
```
The hint is not applied! Only with `--pos` 2,13-20 do the brackets disappear.
I don't think the location of the warning is wrong, `--pos` should work with 2,9, as it is the start of the hint.

**Comment by mpickering** [comment]
But the problem isn't at 2,9. Any other behaviour is confusing imo.

**Comment by mrBliss** [comment]
Alright, but consider my use case: I'm writing some elisp code that uses the flycheck-hlint checker to easily let the user apply suggested refactorings (using `hlint-refactor.el`). All this on the fly, without having to invoke a <kbd>M-x</kbd> command (just <kbd>C-c C-y</kbd>) or switch buffers. So my code uses the hlint warning position as `--pos` argument. If this warning position is not the one `--pos` expects, the whole thing falls apart.
A `--span 2,9-2,20` argument would work well too. If multiple refactorings are in the given span, they could all be applied.

**Comment by mpickering** [comment]
Maybe, but it is possible to get the correct source locations by calling `hlint --serialise`. 

In fact, this is how the integration with hlint currently works, the output of that command is piped into the executable provided by the package and the hints then applied.

Seems like that would be more suitable for your purpose? The problem with the `--span` option is that if there are overlapping hints then it is unclear which one is intended to be applied and it is often not possible to apply both.

**Comment by mrBliss** [comment]
Ah, I didn't know about `hlint --serialise`. That suits my purpose, thanks!
