### ISSUE TITLE
Applying eta reduce does not work

### ISSUE THREAD

**Issue by rikvdkleij** [mpickering/apply-refact#25]
For example:
`foo x = (+1) x`

Hint gives suggestion to eta reduce to:
`foo = (+1)`

`stack exec -- hlint Foo.hs --refactor --refactor-options="--pos 30,1"`
returns no changes.

**Comment by mpickering** [comment]
The hint is not implemented. I found it difficult to implement properly and have since stopped working on the project.

**Comment by mpickering** [comment]
See #3.

**Comment by rikvdkleij** [comment]
Thanks for quick reply!

I just integrated your tool in IntelliJ-Haskell plugin and it works very nice in general. 

Do you mean this project is not maintained anymore? That would be a pity. Or are just eta reduce suggestions not supported?

**Comment by mpickering** [comment]
I do maintenance but I don't plan to implement the eta-reduce myself at the moment.
