### ISSUE TITLE
no way to specify out-of-band pragmas

### ISSUE THREAD

**Issue by mwotton** [mpickering/apply-refact#26]
we tend to specify pragmas in stack.yaml and .ghci - would be nice if refactor could take account of one or the other.

**Comment by eborden** [comment]
Just ran in to this. Another option is to follow the example of other tools like `hlint` and `brittany` and provide a `yaml` file for various configurations.

**Comment by mpickering** [comment]
Patch accepted but I'm not intended to implement it myself.

**Comment by zliu41** [comment]
HLint now passes pragmas to apply-refact via `-X`.
