### ISSUE TITLE
Stack Installation Error: Plan Construction Fails with GHC 8.0.2

### ISSUE THREAD

**Issue by functionallyliterate** [mpickering/apply-refact#29]
Hi,
Forgive my ignorance, I am new to Haskell, but I am having trouble installing apply-refact with stack. I am using GHC 8.0.2 and receive the following message during installation:
![apply_refact](https://user-images.githubusercontent.com/8809492/27560735-559efc7e-5a93-11e7-8d29-26e43c9e45ae.png)

Any assistance would be great, I am trying to install apply-refact as a dependency of using the spacemacs Haskell layer.

Thanks in advance.

**Comment by mpickering** [comment]
I don't know what stack is doing but you need to install `apply-refact-0.3.0.1` as that is the version which works for `ghc-8.0.2`. `apply-refact-0.4.0.0` is for `ghc-8.2.0`.

**Comment by functionallyliterate** [comment]
That worked! Thanks for the assistance.
