### ISSUE TITLE
Installation problem: apply-refract requires GHC 8.2 but stack nightly resolver only supports 8.0.2

### ISSUE THREAD

**Issue by ahri** [mpickering/apply-refact#31]
$ stack --resolver=nightly install apply-refact
    Selected resolver: nightly-2017-06-30

    Error: While constructing the build plan, the following exceptions were encountered:

    In the dependencies for apply-refact-0.4.0.0:
        ghc-8.0.2 must match >=8.2.0 && <8.3

    Plan construction failed.

**Comment by mpickering** [comment]
See #30 #29, you need to use `apply-refact-0.3.0.1` with 8.0.2 as the version bounds suggest.

**Comment by ahri** [comment]
Thanks, I should have searched.

Might it not be helpful to silly newbies like myself if your installation instuructions read something like:

For GHC 8.0.2: `stack install apply-refact-0.3.0.1`
For GHC 8.2: `stack install apply-refact-0.4.0.0`

Just to avoid these issues, I mean?
