### ISSUE TITLE
Parse error on LambdaCase

### ISSUE THREAD

**Issue by txsmith** [mpickering/apply-refact#33]
When I try to apply hlint suggestions to a file that contains `\case -> ...` expressions, apply-refact throws a parser error when LambdaCase is not in a `LANGUAGE` pragma inside the source file:

```
refactor: (RealSrcSpan SrcSpanOneLine "src/Main.hs" 6 6 10,"parse error on input \8216case\8217")
CallStack (from HasCallStack):
  error, called at src/Main.hs:189:22 in main:Main
```

**Steps to reproduce:**

- `stack new test simple && cd test`
- Edit `src/Main.hs` to:
```haskell
module Main where

main = putStrLn "hello world"

f = \case [] -> 0
```
- Run `refactor src/Main.hs` and observe the error mentioned above.
- Now add `{-# LANGUAGE LambdaCase #-}` to the Main module, try again, the error disappears.

What confuses me is that this behavior seems to be unique to LambdaCase. For other extensions (like RecordWildCards or TypeApplications) hlint works just fine even without the appropriate `LANGUAGE` pragmas. It would be really nice to use hlint with refactorings on projects where LambdaCase is in the `default-extensions` section in a cabal-file and thus not declared in any source file.

**Comment by TOTBWF** [comment]
I'm experiencing this as well, it looks like this is an issue with [ghc-exactprint](https://github.com/alanz/ghc-exactprint)

**Comment by creichert** [comment]
I hit this as well running automated refactors with hlint when using default-extensions in a cabal file.

**Comment by zliu41** [comment]
This is fixed in https://github.com/ndmitchell/hlint/pull/1027. HLint now passes extensions to apply-refact, which means HLint and apply-refact use the same extensions, unless you enable or disable additional extensions using the `--refactor-options` flag.
