### ISSUE TITLE
removing brackets on patterns may generate invalid code

### ISSUE THREAD

**Issue by expipiplus1** [mpickering/apply-refact#40]
Removing the redundant brackets from this pattern: `a = \(~x) -> x` produces `a = \~x -> x` which is not valid, there must be a space between `\` and `~`

**Comment by expipiplus1** [comment]
(Thanks for the super tool btw!)

**Comment by zliu41** [comment]
Are you saying HLint suggests removing the brackets, or HLint doesn't but apply-refact still removes the brackets? I know this is more than a year old but neither seems to be the case now. Please feel free to reopen otherwise.

**Comment by expipiplus1** [comment]
hmm, can't remember. Glad that it's been corrected though!
