### ISSUE TITLE
GHC 8.8 support

### ISSUE THREAD

**Issue by InBetweenNames** [mpickering/apply-refact#49]
GHC 8.8.1 is out now -- any idea how to get apply-refact to build with it?  It seems like some internals might have changed.

**Comment by alanz** [comment]
FYI I just published ghc-exactprint 0.6.2 which supports GHC 8.8.1 (rc).

**Comment by Avi-D-coder** [comment]
@mpickering can you push a new version to hackage now that it compiles on 8.8
