### ISSUE TITLE
Applying "Use &&" leaves a comma

### ISSUE THREAD

**Issue by niteria** [mpickering/apply-refact#5]
Thank you for the awesome tool! Combined with HLint it's really powerful. 

Repro.hs:
```
athing = and [a, b]
```

The suggestion:

```
Repro.hs:2:5: Warning: Use &&
Found:
  and [a, b]
Why not:
  a && b

1 suggestion
```
Result (~/local/hlint/dist/build/hlint/hlint --refactor --with-refactor=$HOME/local/apply-refact/dist/build/refactor/refactor ~/Repro.hs):

```
athing = a, && b
```

**Comment by mpickering** [comment]
This is an unfortunate consequence of how the annotations are arranged in GHC. I will have to think carefully how to fix it so things continue to work in the general case.

**Comment by mpickering** [comment]
Much easier to fix than I thought.

**Comment by niteria** [comment]
Thank you!

2015-10-15 21:34 GMT+01:00 Matthew Pickering <notifications@github.com>:
