### ISSUE TITLE
a = -b/c round-trips to a =b/c

### ISSUE THREAD

**Issue by niteria** [mpickering/apply-refact#6]
```
$ cat ~/Repro.hs
a = -b/c
$ echo [] | $HOME/local/apply-refact/dist/build/refactor/refactor --roundtrip ~/Repro.hs
Applying 0 hints
a =b/c
```

**Comment by mpickering** [comment]
Thanks, I am moving this issue to the `ghc-exactprint` issue tracker.

**Comment by niteria** [comment]
Thanks!

**Comment by mpickering** [comment]
It actually seems to work properly with `ghc-exactprint` so I will leave it here.

**Comment by mpickering** [comment]
OK, this is a bug in the `applyFixities` function if someone gets to this before me.

**Comment by mpickering** [comment]
Fixed.. for now. I'm not convinced my solution is very robust so please report back if there are any more problems with this.
