### ISSUE TITLE
uncurry (.=) p HLint suggestion turns into uncurry .= p

### ISSUE THREAD

**Issue by niteria** [mpickering/apply-refact#7]
```
$ cat ~/Repro.hs
f p = fst p .= snd p
$ ~/local/hlint/dist/build/hlint/hlint ~/Repro.hs
Repro.hs:1:7: Error: Evaluate
Found:
  fst p .= snd p
Why not:
  uncurry (.=) p

1 suggestion
$ ~/local/hlint/dist/build/hlint/hlint --refactor --with-refactor=$HOME/local/apply-refact/dist/build/refactor/refactor ~/Repro.hs
f p = uncurry .= p
```

**Comment by mpickering** [comment]
Will have to look at this closely. IIRC, difficult to fix as the HSE and GHC representations are a bit different.

**Comment by mpickering** [comment]
I think this is where the problems start. https://github.com/ndmitchell/hlint/blob/master/src/Hint/Match.hs#L188

I don't think this will be easy to fix like I suspected in my first message. Will look a bit more when I have some more time.

**Comment by zliu41** [comment]
Fixed in the above PR.
